# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create a GitHub release with built RPMs"
        required: false
        type: boolean
        default: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: fedora:41

    outputs:
      MUTTER_VERSION: ${{ steps.extract_versions.outputs.MUTTER_VERSION }}
      GCC_VERSION: ${{ steps.extract_versions.outputs.GCC_VERSION }}
      RELEASE_TAG: ${{ steps.extract_versions.outputs.RELEASE_TAG }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install extra build dependencies
        run: dnf in -y git rpm-build

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history, including tags

      - name: Extract versions and determine release tag
        id: extract_versions
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

          MUTTER_VERSION=$(sed -n 's/^Version:\s*\(.*\)/\1/p' rpmbuild/SPECS/mutter.spec)
          GCC_VERSION=$(sed -n 's/^Version:\s*\(.*\)/\1/p' rpmbuild/SPECS/gnome-control-center.spec)

          BASE_TAG="${GCC_VERSION}-v"
          EXISTING_TAG=$(git tag --list "${BASE_TAG}*" | sed 's/.*-v//' | sort -V | tail -n 1)

          if [[ -z "$EXISTING_TAG" ]]; then
            RELEASE_TAG="${BASE_TAG}1"
          else
            RELEASE_TAG="${BASE_TAG}$((EXISTING_TAG + 1))"
          fi

          echo "MUTTER_VERSION=$MUTTER_VERSION" >> $GITHUB_OUTPUT
          echo "GCC_VERSION=$GCC_VERSION" >> $GITHUB_OUTPUT
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Install mutter dependencies
        run: dnf builddep -y rpmbuild/SPECS/mutter.spec

      - name: Install gcc dependencies
        run: dnf builddep -y rpmbuild/SPECS/gnome-control-center.spec

      - name: create target directory
        run: mkdir rpms

      - name: build mutter binary
        run: rpmbuild -D "_sourcedir $PWD/rpmbuild/SOURCES" -D "_rpmdir $PWD/rpms" -D "_srcrpmdir ${PWD}/rpms" --clean -ba rpmbuild/SPECS/mutter.spec

      - name: build gcc binary
        run: rpmbuild -D "_sourcedir $PWD/rpmbuild/SOURCES" -D "_rpmdir $PWD/rpms" -D "_srcrpmdir ${PWD}/rpms" --clean -ba rpmbuild/SPECS/gnome-control-center.spec

      - name: Archive RPM packages
        uses: actions/upload-artifact@v4
        with:
          name: rpms-fedora
          path: |
            rpms/**/*.rpm

  release:
    if: github.event.inputs.create_release == 'true'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download built RPMs
        uses: actions/download-artifact@v4
        with:
          name: rpms-fedora
          path: rpms

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: rpms/**/*.rpm
          tag_name: ${{ needs.build.outputs.RELEASE_TAG }}
          name: "mutter-${{ needs.build.outputs.MUTTER_VERSION }}, gnome-control-center-${{ needs.build.outputs.GCC_VERSION }}"
          body: "Automated release for ${{ needs.build.outputs.RELEASE_TAG }}"
          generate_release_notes: true
          draft: false
          prerelease: false
